### PR TITLE
Mail template spelling fixes

### PR DESCRIPTION
**Pull request by k-korn**
Small corrections to improve English translation.

### CODE REVIEW

**Comment by redhook62** [comment]
New Build Tomorrow

**Comment by redhook62** [comment]
Done

**Comment by k-korn** [comment]
Done, but has it been merged?

**Comment by redhook62** [comment]
In principle Yes,

But I will check this afternoon.
There will be a new build for tomorrow, your changes will certainly be there.

thanks again

redhook

**Comment by redhook62** [comment]
@k-korn 

This time, it is verified and present in build 3.0.2007.2
Sorry for the setback.

Regards

**Comment by ImenTurki** [comment]
hello , i dont know if its in your issue , i want to change the  email template and text, have you any idea ?

**Pull request closed without merging**
